#!/bin/sh

set -e

# If lsb_release is missing, just do nothing.
DISTRO=`lsb_release -si` || true

case $DISTRO in
    'Ubuntu'|'Debian')
        sed -i -e 's/\(^GRUB_CMDLINE_LINUX.*\)"$/\1 elevator=noop"/' /etc/default/grub
        update-grub
        ;;
    'Fedora')
        if [ -f /boot/grub2/grub.cfg ]; then
            sed -i -e 's/\(^GRUB_CMDLINE_LINUX.*\)"$/\1 elevator=noop"/' /etc/default/grub
            grub2-mkconfig -o /boot/grub2/grub.cfg
        fi
        ;;
esac
