#!/bin/sh
set -e

[ -n "$TARGET_ROOT" ]

ANACONDA_FILE=Anaconda-1.8.0-Linux-x86_64.sh
CACHED_FILE=$DIB_IMAGE_CACHE/$ANACONDA_FILE
URL=http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-1.8.0-Linux-x86_64.sh

if [ -n "$DIB_OFFLINE" -a -f "$CACHED_FILE" ] ; then
    echo "Not checking freshness of cached $CACHED_FILE."
else
    $TMP_HOOKS_PATH/bin/cache-url $URL $CACHED_FILE
fi

sudo cp $CACHED_FILE $TARGET_ROOT/root
