#!/bin/bash

case $DIB_RELEASE in
    'wheezy'|'jessie')
	echo "deb ${DIB_MIRROR} ${DIB_RELEASE} main contrib non-free
# deb-src ${DIB_MIRROR} ${DIB_RELEASE} main contrib non-free

deb ${DIB_MIRROR} ${DIB_RELEASE}-updates main contrib non-free
# deb-src ${DIB_MIRROR} ${DIB_RELEASE}-updates main contrib non-free
deb http://security.debian.org/ ${DIB_RELEASE}/updates main contrib non-free
# deb-src http://security.debian.org/ ${DIB_RELEASE}/updates main contrib non-free

deb ${DIB_MIRROR} ${DIB_RELEASE}-backports main contrib non-free
# deb-src ${DIB_MIRROR} ${DIB_RELEASE}-backports main contrib non-free
" > /etc/apt/sources.list
    ;;
    *)
	echo "deb ${DIB_MIRROR} ${DIB_RELEASE} main contrib non-free
# deb-src ${DIB_MIRROR} ${DIB_RELEASE} main contrib non-free
" > /etc/apt/sources.list
    ;;
esac
