#!/bin/sh

set -e

# If lsb_release is missing, just do nothing.
DISTRO=`lsb_release -si` || true

sed -i -e 's/\(^GRUB_CMDLINE_LINUX=.*\)"$/\1 console=ttyS0"/' /etc/default/grub
sed -i -e 's/\(^GRUB_CMDLINE_LINUX_DEFAULT=.*\)"$/GRUB_CMDLINE_LINUX_DEFAULT=""/' /etc/default/grub
update-grub
