#!/bin/sh
# -*- mode: sh -*-

set -e

# If lsb_release is missing, just do nothing.
DISTRO=`lsb_release -si` || true

case $DISTRO in
    'Ubuntu')
        sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu/http:\/\/mirror.aarnet.edu.au\/pub\/ubuntu\/archive\//g' /etc/apt/sources.list
        sed -i 's/http:\/\/security.ubuntu.com\/ubuntu/http:\/\/mirror.aarnet.edu.au\/pub\/ubuntu\/archive\//g' /etc/apt/sources.list
        ;;
esac
